// Copyright and license: see repository LICENSE (MIT).
//
// Share/Block wire schema for go-crypto-pool, exchanged between leaf
// binaries (leaf-direct, leaf-solo, leaf-proxy) and the backend over the
// HTTP+Protobuf edge transport (see internal/leaflib/transport).
//
// Design notes / deltas from the legacy SXMR proto2 schema
// (nodejs-pool-sxmr's Share/Block), which this schema generalizes for a
// multi-algo, multi-network omni-pool:
//
//   - Algo is now a required, explicit field on every Share/Block. The
//     legacy schema had no coin/algo tag at all because it assumed one
//     deployment per coin. go-crypto-pool serves RXT/C29/SHA3X/RXM out of
//     one backend, so every message must self-identify its algo.
//   - Network (MAINNET/TESTNET) is likewise now a required, explicit
//     field on every Share/Block, per the project requirement to support
//     testnet operation for all algos during development.
//   - The legacy `bitcoin bool` payout-currency flag is dropped entirely —
//     it was a Monero-fork-specific hack that doesn't generalize to Tari's
//     multi-algo model and isn't used here.
//   - The legacy `trustedShare bool` field is carried forward as
//     `trusted_share` — it is still actively used in production
//     (accounting/payout trust-boundary flag), do not drop it.
//   - `blockHeight` is int64, not int32 (legacy proto2 used int32, which
//     is a real overflow bug waiting to happen well before height 2^31).
//   - The legacy RandomX-specific trio (`blobData`, `minerHex`,
//     `seedHash`) is replaced by a `oneof raw_proof` with one message per
//     algo family, since C29 (Cuckaroo29 cycle-proof) and SHA3X (plain
//     hash) are structurally different from RandomX's blob/seed/hash
//     model and don't fit the same three fields. This raw proof is
//     optional supporting data for a future secondary/audit validator;
//     the backend itself does NOT re-validate PoW (see AGENTS.md — it's a
//     trust boundary, leaves own all algo-specific validation).
//
// NOTE on C29Proof: field shapes were checked against the real Tari C29
// miner implementation (go-tari-c29-solo-stratum's SubmitJob, via
// snipa22/powkit's cuckoo.Client.Verify) as part of building the
// internal/leaflib/validator package. `edge_bits` + repeated `cycle` (the
// 42-edge Cuckaroo29 cycle, u64 edge nonces) matches the real proof shape.
// `header` was ADDED here (it did not exist in the original placeholder)
// because the real cycle-verify primitive needs header/merge-mining-hash
// material to derive its siphash keys (see legacy SubmitJob:
// `nonceBytes = nonce || job.BlockResult.MergeMiningHash`, hashed to
// derive `hasher.Verify(nonceBytes, submittedWork.POW)`'s keys) — the
// original placeholder had no field carrying that, which would have made
// real verification impossible. See internal/leaflib/validator for the
// port.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: internal/proto/share.proto

package poolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Algo identifies the mining algorithm / share stream a message belongs
// to. go-crypto-pool is an omni-pool serving all four from one backend,
// so this tag is mandatory on every Share and Block.
type Algo int32

const (
	Algo_ALGO_UNSPECIFIED Algo = 0
	Algo_ALGO_RXT         Algo = 1 // RandomX-Tari
	Algo_ALGO_C29         Algo = 2 // Cuckaroo/Cuckatoo29
	Algo_ALGO_SHA3X       Algo = 3 // SHA3-256 (Tari merge-mining / SHA3X)
	Algo_ALGO_RXM         Algo = 4 // RandomX-Monero-family
)

// Enum value maps for Algo.
var (
	Algo_name = map[int32]string{
		0: "ALGO_UNSPECIFIED",
		1: "ALGO_RXT",
		2: "ALGO_C29",
		3: "ALGO_SHA3X",
		4: "ALGO_RXM",
	}
	Algo_value = map[string]int32{
		"ALGO_UNSPECIFIED": 0,
		"ALGO_RXT":         1,
		"ALGO_C29":         2,
		"ALGO_SHA3X":       3,
		"ALGO_RXM":         4,
	}
)

func (x Algo) Enum() *Algo {
	p := new(Algo)
	*p = x
	return p
}

func (x Algo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algo) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_share_proto_enumTypes[0].Descriptor()
}

func (Algo) Type() protoreflect.EnumType {
	return &file_internal_proto_share_proto_enumTypes[0]
}

func (x Algo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algo.Descriptor instead.
func (Algo) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{0}
}

// Network distinguishes mainnet from testnet deployments. Required on
// every Share/Block so a single backend can safely serve both without
// cross-contaminating payout/accounting state.
type Network int32

const (
	Network_NETWORK_UNSPECIFIED Network = 0
	Network_NETWORK_MAINNET     Network = 1
	Network_NETWORK_TESTNET     Network = 2
)

// Enum value maps for Network.
var (
	Network_name = map[int32]string{
		0: "NETWORK_UNSPECIFIED",
		1: "NETWORK_MAINNET",
		2: "NETWORK_TESTNET",
	}
	Network_value = map[string]int32{
		"NETWORK_UNSPECIFIED": 0,
		"NETWORK_MAINNET":     1,
		"NETWORK_TESTNET":     2,
	}
)

func (x Network) Enum() *Network {
	p := new(Network)
	*p = x
	return p
}

func (x Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Network) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_share_proto_enumTypes[1].Descriptor()
}

func (Network) Type() protoreflect.EnumType {
	return &file_internal_proto_share_proto_enumTypes[1]
}

func (x Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Network.Descriptor instead.
func (Network) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{1}
}

// PoolType mirrors the legacy SXMR POOLTYPE enum — this part of the
// legacy design generalizes fine as-is.
type PoolType int32

const (
	PoolType_POOL_TYPE_UNSPECIFIED PoolType = 0
	PoolType_POOL_TYPE_PPLNS       PoolType = 1
	PoolType_POOL_TYPE_PPS         PoolType = 2
	PoolType_POOL_TYPE_PROP        PoolType = 3
	PoolType_POOL_TYPE_SOLO        PoolType = 4
)

// Enum value maps for PoolType.
var (
	PoolType_name = map[int32]string{
		0: "POOL_TYPE_UNSPECIFIED",
		1: "POOL_TYPE_PPLNS",
		2: "POOL_TYPE_PPS",
		3: "POOL_TYPE_PROP",
		4: "POOL_TYPE_SOLO",
	}
	PoolType_value = map[string]int32{
		"POOL_TYPE_UNSPECIFIED": 0,
		"POOL_TYPE_PPLNS":       1,
		"POOL_TYPE_PPS":         2,
		"POOL_TYPE_PROP":        3,
		"POOL_TYPE_SOLO":        4,
	}
)

func (x PoolType) Enum() *PoolType {
	p := new(PoolType)
	*p = x
	return p
}

func (x PoolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_share_proto_enumTypes[2].Descriptor()
}

func (PoolType) Type() protoreflect.EnumType {
	return &file_internal_proto_share_proto_enumTypes[2]
}

func (x PoolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolType.Descriptor instead.
func (PoolType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{2}
}

// RandomXProof carries the legacy blob/seed/result trio for RXT and RXM,
// which are both RandomX-family algos and share the same proof shape.
type RandomXProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          []byte                 `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`                            // block template blob that was hashed
	SeedHash      []byte                 `protobuf:"bytes,2,opt,name=seed_hash,json=seedHash,proto3" json:"seed_hash,omitempty"`    // RandomX seed hash in effect for this height
	ResultHex     string                 `protobuf:"bytes,3,opt,name=result_hex,json=resultHex,proto3" json:"result_hex,omitempty"` // claimed PoW hash result, hex-encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomXProof) Reset() {
	*x = RandomXProof{}
	mi := &file_internal_proto_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomXProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomXProof) ProtoMessage() {}

func (x *RandomXProof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomXProof.ProtoReflect.Descriptor instead.
func (*RandomXProof) Descriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{0}
}

func (x *RandomXProof) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *RandomXProof) GetSeedHash() []byte {
	if x != nil {
		return x.SeedHash
	}
	return nil
}

func (x *RandomXProof) GetResultHex() string {
	if x != nil {
		return x.ResultHex
	}
	return ""
}

// C29Proof carries a Cuckaroo/Cuckatoo29 cycle-proof. See the top-of-file
// note: field shapes are checked against the real go-tari-c29-solo-stratum
// SubmitJob verification path.
type C29Proof struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EdgeBits uint32                 `protobuf:"varint,1,opt,name=edge_bits,json=edgeBits,proto3" json:"edge_bits,omitempty"` // graph size parameter (29 for Tari's Cuckaroo29)
	Cycle    []uint64               `protobuf:"varint,2,rep,packed,name=cycle,proto3" json:"cycle,omitempty"`                // the proof cycle's 42 edge nonces
	// header is the nonce-independent header/merge-mining-hash material the
	// real verifier hashes (blake2b-256) to derive its siphash keys — ported
	// from go-tari-c29-solo-stratum's `nonceBytes = nonce || MergeMiningHash`
	// construction. Added in this pass: the original placeholder omitted it,
	// which would have made real cycle verification impossible.
	Header        []byte `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Nonce         uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"` // the submitted nonce, combined with header per above
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C29Proof) Reset() {
	*x = C29Proof{}
	mi := &file_internal_proto_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C29Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C29Proof) ProtoMessage() {}

func (x *C29Proof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C29Proof.ProtoReflect.Descriptor instead.
func (*C29Proof) Descriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{1}
}

func (x *C29Proof) GetEdgeBits() uint32 {
	if x != nil {
		return x.EdgeBits
	}
	return 0
}

func (x *C29Proof) GetCycle() []uint64 {
	if x != nil {
		return x.Cycle
	}
	return nil
}

func (x *C29Proof) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *C29Proof) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// SHA3XProof carries a straight header+nonce pair for the SHA3X algo,
// which has no intermediate blob/seed concept the way RandomX does.
type SHA3XProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []byte                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nonce         uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHA3XProof) Reset() {
	*x = SHA3XProof{}
	mi := &file_internal_proto_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHA3XProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHA3XProof) ProtoMessage() {}

func (x *SHA3XProof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHA3XProof.ProtoReflect.Descriptor instead.
func (*SHA3XProof) Descriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{2}
}

func (x *SHA3XProof) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SHA3XProof) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// Share represents one accepted share submission from a leaf to the
// backend. Every field the backend needs for accounting/payout is
// present without decoding raw_proof; raw_proof is optional supporting
// data for a future secondary/audit validator only.
type Share struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Algo           Algo                   `protobuf:"varint,1,opt,name=algo,proto3,enum=pool.v1.Algo" json:"algo,omitempty"`
	Network        Network                `protobuf:"varint,2,opt,name=network,proto3,enum=pool.v1.Network" json:"network,omitempty"`
	Shares         int64                  `protobuf:"varint,3,opt,name=shares,proto3" json:"shares,omitempty"`
	PaymentAddress string                 `protobuf:"bytes,4,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	FoundBlock     bool                   `protobuf:"varint,5,opt,name=found_block,json=foundBlock,proto3" json:"found_block,omitempty"`
	PaymentId      *string                `protobuf:"bytes,6,opt,name=payment_id,json=paymentId,proto3,oneof" json:"payment_id,omitempty"`
	PoolType       PoolType               `protobuf:"varint,7,opt,name=pool_type,json=poolType,proto3,enum=pool.v1.PoolType" json:"pool_type,omitempty"`
	PoolId         int32                  `protobuf:"varint,8,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	BlockDiff      int64                  `protobuf:"varint,9,opt,name=block_diff,json=blockDiff,proto3" json:"block_diff,omitempty"`
	BlockHeight    int64                  `protobuf:"varint,10,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"` // int64: legacy int32 overflows well before real chain heights
	Timestamp      int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Identifier     string                 `protobuf:"bytes,12,opt,name=identifier,proto3" json:"identifier,omitempty"` // worker/rig identifier
	// raw_proof is optional, algo-tagged proof material kept around for a
	// future audit/secondary-validation path. The backend does not decode
	// or validate this today.
	//
	// Types that are valid to be assigned to RawProof:
	//
	//	*Share_RandomxProof
	//	*Share_C29Proof
	//	*Share_Sha3XProof
	RawProof isShare_RawProof `protobuf_oneof:"raw_proof"`
	// trusted_share carried over from the legacy schema — actively used in
	// production (accounting/payout trust-boundary flag), do not drop.
	TrustedShare  bool `protobuf:"varint,16,opt,name=trusted_share,json=trustedShare,proto3" json:"trusted_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_internal_proto_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{3}
}

func (x *Share) GetAlgo() Algo {
	if x != nil {
		return x.Algo
	}
	return Algo_ALGO_UNSPECIFIED
}

func (x *Share) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

func (x *Share) GetShares() int64 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *Share) GetPaymentAddress() string {
	if x != nil {
		return x.PaymentAddress
	}
	return ""
}

func (x *Share) GetFoundBlock() bool {
	if x != nil {
		return x.FoundBlock
	}
	return false
}

func (x *Share) GetPaymentId() string {
	if x != nil && x.PaymentId != nil {
		return *x.PaymentId
	}
	return ""
}

func (x *Share) GetPoolType() PoolType {
	if x != nil {
		return x.PoolType
	}
	return PoolType_POOL_TYPE_UNSPECIFIED
}

func (x *Share) GetPoolId() int32 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *Share) GetBlockDiff() int64 {
	if x != nil {
		return x.BlockDiff
	}
	return 0
}

func (x *Share) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Share) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Share) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Share) GetRawProof() isShare_RawProof {
	if x != nil {
		return x.RawProof
	}
	return nil
}

func (x *Share) GetRandomxProof() *RandomXProof {
	if x != nil {
		if x, ok := x.RawProof.(*Share_RandomxProof); ok {
			return x.RandomxProof
		}
	}
	return nil
}

func (x *Share) GetC29Proof() *C29Proof {
	if x != nil {
		if x, ok := x.RawProof.(*Share_C29Proof); ok {
			return x.C29Proof
		}
	}
	return nil
}

func (x *Share) GetSha3XProof() *SHA3XProof {
	if x != nil {
		if x, ok := x.RawProof.(*Share_Sha3XProof); ok {
			return x.Sha3XProof
		}
	}
	return nil
}

func (x *Share) GetTrustedShare() bool {
	if x != nil {
		return x.TrustedShare
	}
	return false
}

type isShare_RawProof interface {
	isShare_RawProof()
}

type Share_RandomxProof struct {
	RandomxProof *RandomXProof `protobuf:"bytes,13,opt,name=randomx_proof,json=randomxProof,proto3,oneof"`
}

type Share_C29Proof struct {
	C29Proof *C29Proof `protobuf:"bytes,14,opt,name=c29_proof,json=c29Proof,proto3,oneof"`
}

type Share_Sha3XProof struct {
	Sha3XProof *SHA3XProof `protobuf:"bytes,15,opt,name=sha3x_proof,json=sha3xProof,proto3,oneof"`
}

func (*Share_RandomxProof) isShare_RawProof() {}

func (*Share_C29Proof) isShare_RawProof() {}

func (*Share_Sha3XProof) isShare_RawProof() {}

// Block represents a block found and reported by a leaf.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          Algo                   `protobuf:"varint,1,opt,name=algo,proto3,enum=pool.v1.Algo" json:"algo,omitempty"`
	Network       Network                `protobuf:"varint,2,opt,name=network,proto3,enum=pool.v1.Network" json:"network,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Difficulty    int64                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Shares        int64                  `protobuf:"varint,5,opt,name=shares,proto3" json:"shares,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PoolType      PoolType               `protobuf:"varint,7,opt,name=pool_type,json=poolType,proto3,enum=pool.v1.PoolType" json:"pool_type,omitempty"`
	Unlocked      bool                   `protobuf:"varint,8,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Valid         bool                   `protobuf:"varint,9,opt,name=valid,proto3" json:"valid,omitempty"`
	Value         *int64                 `protobuf:"varint,10,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Height        int64                  `protobuf:"varint,11,opt,name=height,proto3" json:"height,omitempty"` // block_height wasn't in the legacy Block message; added since the backend needs it for the same overflow reasons as Share
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_internal_proto_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_proto_share_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetAlgo() Algo {
	if x != nil {
		return x.Algo
	}
	return Algo_ALGO_UNSPECIFIED
}

func (x *Block) GetNetwork() Network {
	if x != nil {
		return x.Network
	}
	return Network_NETWORK_UNSPECIFIED
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetDifficulty() int64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Block) GetShares() int64 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetPoolType() PoolType {
	if x != nil {
		return x.PoolType
	}
	return PoolType_POOL_TYPE_UNSPECIFIED
}

func (x *Block) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *Block) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Block) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_internal_proto_share_proto protoreflect.FileDescriptor

const file_internal_proto_share_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/share.proto\x12\apool.v1\"^\n" +
	"\fRandomXProof\x12\x12\n" +
	"\x04blob\x18\x01 \x01(\fR\x04blob\x12\x1b\n" +
	"\tseed_hash\x18\x02 \x01(\fR\bseedHash\x12\x1d\n" +
	"\n" +
	"result_hex\x18\x03 \x01(\tR\tresultHex\"k\n" +
	"\bC29Proof\x12\x1b\n" +
	"\tedge_bits\x18\x01 \x01(\rR\bedgeBits\x12\x14\n" +
	"\x05cycle\x18\x02 \x03(\x04R\x05cycle\x12\x16\n" +
	"\x06header\x18\x03 \x01(\fR\x06header\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\":\n" +
	"\n" +
	"SHA3XProof\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\"\x8e\x05\n" +
	"\x05Share\x12!\n" +
	"\x04algo\x18\x01 \x01(\x0e2\r.pool.v1.AlgoR\x04algo\x12*\n" +
	"\anetwork\x18\x02 \x01(\x0e2\x10.pool.v1.NetworkR\anetwork\x12\x16\n" +
	"\x06shares\x18\x03 \x01(\x03R\x06shares\x12'\n" +
	"\x0fpayment_address\x18\x04 \x01(\tR\x0epaymentAddress\x12\x1f\n" +
	"\vfound_block\x18\x05 \x01(\bR\n" +
	"foundBlock\x12\"\n" +
	"\n" +
	"payment_id\x18\x06 \x01(\tH\x01R\tpaymentId\x88\x01\x01\x12.\n" +
	"\tpool_type\x18\a \x01(\x0e2\x11.pool.v1.PoolTypeR\bpoolType\x12\x17\n" +
	"\apool_id\x18\b \x01(\x05R\x06poolId\x12\x1d\n" +
	"\n" +
	"block_diff\x18\t \x01(\x03R\tblockDiff\x12!\n" +
	"\fblock_height\x18\n" +
	" \x01(\x03R\vblockHeight\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"identifier\x18\f \x01(\tR\n" +
	"identifier\x12<\n" +
	"\rrandomx_proof\x18\r \x01(\v2\x15.pool.v1.RandomXProofH\x00R\frandomxProof\x120\n" +
	"\tc29_proof\x18\x0e \x01(\v2\x11.pool.v1.C29ProofH\x00R\bc29Proof\x126\n" +
	"\vsha3x_proof\x18\x0f \x01(\v2\x13.pool.v1.SHA3XProofH\x00R\n" +
	"sha3xProof\x12#\n" +
	"\rtrusted_share\x18\x10 \x01(\bR\ftrustedShareB\v\n" +
	"\traw_proofB\r\n" +
	"\v_payment_id\"\xdf\x02\n" +
	"\x05Block\x12!\n" +
	"\x04algo\x18\x01 \x01(\x0e2\r.pool.v1.AlgoR\x04algo\x12*\n" +
	"\anetwork\x18\x02 \x01(\x0e2\x10.pool.v1.NetworkR\anetwork\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x03R\n" +
	"difficulty\x12\x16\n" +
	"\x06shares\x18\x05 \x01(\x03R\x06shares\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12.\n" +
	"\tpool_type\x18\a \x01(\x0e2\x11.pool.v1.PoolTypeR\bpoolType\x12\x1a\n" +
	"\bunlocked\x18\b \x01(\bR\bunlocked\x12\x14\n" +
	"\x05valid\x18\t \x01(\bR\x05valid\x12\x19\n" +
	"\x05value\x18\n" +
	" \x01(\x03H\x00R\x05value\x88\x01\x01\x12\x16\n" +
	"\x06height\x18\v \x01(\x03R\x06heightB\b\n" +
	"\x06_value*V\n" +
	"\x04Algo\x12\x14\n" +
	"\x10ALGO_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bALGO_RXT\x10\x01\x12\f\n" +
	"\bALGO_C29\x10\x02\x12\x0e\n" +
	"\n" +
	"ALGO_SHA3X\x10\x03\x12\f\n" +
	"\bALGO_RXM\x10\x04*L\n" +
	"\aNetwork\x12\x17\n" +
	"\x13NETWORK_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNETWORK_MAINNET\x10\x01\x12\x13\n" +
	"\x0fNETWORK_TESTNET\x10\x02*u\n" +
	"\bPoolType\x12\x19\n" +
	"\x15POOL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPOOL_TYPE_PPLNS\x10\x01\x12\x11\n" +
	"\rPOOL_TYPE_PPS\x10\x02\x12\x12\n" +
	"\x0ePOOL_TYPE_PROP\x10\x03\x12\x12\n" +
	"\x0ePOOL_TYPE_SOLO\x10\x04B9Z7github.com/Snipa22/go-crypto-pool/internal/proto;poolpbb\x06proto3"

var (
	file_internal_proto_share_proto_rawDescOnce sync.Once
	file_internal_proto_share_proto_rawDescData []byte
)

func file_internal_proto_share_proto_rawDescGZIP() []byte {
	file_internal_proto_share_proto_rawDescOnce.Do(func() {
		file_internal_proto_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_share_proto_rawDesc), len(file_internal_proto_share_proto_rawDesc)))
	})
	return file_internal_proto_share_proto_rawDescData
}

var file_internal_proto_share_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_share_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_share_proto_goTypes = []any{
	(Algo)(0),            // 0: pool.v1.Algo
	(Network)(0),         // 1: pool.v1.Network
	(PoolType)(0),        // 2: pool.v1.PoolType
	(*RandomXProof)(nil), // 3: pool.v1.RandomXProof
	(*C29Proof)(nil),     // 4: pool.v1.C29Proof
	(*SHA3XProof)(nil),   // 5: pool.v1.SHA3XProof
	(*Share)(nil),        // 6: pool.v1.Share
	(*Block)(nil),        // 7: pool.v1.Block
}
var file_internal_proto_share_proto_depIdxs = []int32{
	0, // 0: pool.v1.Share.algo:type_name -> pool.v1.Algo
	1, // 1: pool.v1.Share.network:type_name -> pool.v1.Network
	2, // 2: pool.v1.Share.pool_type:type_name -> pool.v1.PoolType
	3, // 3: pool.v1.Share.randomx_proof:type_name -> pool.v1.RandomXProof
	4, // 4: pool.v1.Share.c29_proof:type_name -> pool.v1.C29Proof
	5, // 5: pool.v1.Share.sha3x_proof:type_name -> pool.v1.SHA3XProof
	0, // 6: pool.v1.Block.algo:type_name -> pool.v1.Algo
	1, // 7: pool.v1.Block.network:type_name -> pool.v1.Network
	2, // 8: pool.v1.Block.pool_type:type_name -> pool.v1.PoolType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_share_proto_init() }
func file_internal_proto_share_proto_init() {
	if File_internal_proto_share_proto != nil {
		return
	}
	file_internal_proto_share_proto_msgTypes[3].OneofWrappers = []any{
		(*Share_RandomxProof)(nil),
		(*Share_C29Proof)(nil),
		(*Share_Sha3XProof)(nil),
	}
	file_internal_proto_share_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_share_proto_rawDesc), len(file_internal_proto_share_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_share_proto_goTypes,
		DependencyIndexes: file_internal_proto_share_proto_depIdxs,
		EnumInfos:         file_internal_proto_share_proto_enumTypes,
		MessageInfos:      file_internal_proto_share_proto_msgTypes,
	}.Build()
	File_internal_proto_share_proto = out.File
	file_internal_proto_share_proto_goTypes = nil
	file_internal_proto_share_proto_depIdxs = nil
}
