// Copyright and license: see repository LICENSE (MIT).
//
// Legacy nodejs-pool-sxmr wire schema, hand-modeled on the REAL production
// source of a sibling clone of `nodejs-pool` fetched for this task:
//
//   - `nodejs-pool/lib/data.proto` (the actual proto2 schema `/leafApi`
//     decodes with -- field numbers/types/names below are byte-for-byte
//     identical to that file; this is NOT a reinterpretation or a proto3
//     port, it is proto2, on purpose, matching the real wire format a
//     legacy nodejs-pool-sxmr backend still expects on the wire today).
//   - `nodejs-pool/lib/remoteShare.js` (the real `/leafApi` POST handler
//     that decodes a `WSData` envelope, checks `msgData.key` against
//     `global.config.api.authKey` with `!==`, and dispatches on
//     `msgData.msgType` to SHARE/BLOCK/INVALIDSHARE handling -- see
//     internal/leaflib/legacytransport's package doc comment for the
//     full behavioral notes this schema is paired with).
//
// Non-finding, documented per task instructions: this repo's own
// internal/proto/share.proto previously speculated that an older/
// different legacy Share schema might have existed with `blobData`/
// `minerHex`/`seedHash` fields (RandomX-specific blob/seed/result trio).
// A full check of the real nodejs-pool repository (single-commit git
// history; `git log --all -- '*.proto'` shows exactly one proto file in
// the entire history) found NO such schema anywhere -- `seedHash` only
// ever appears in unrelated block-template construction code
// (`lib/coins/xmr.js`), never as a Share message field. The schema below
// is the one, real, only wire schema `/leafApi` has ever used. Do not
// reintroduce a speculative blobData/minerHex/seedHash Share variant --
// it does not exist in the real legacy source.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: internal/legacyproto/legacy.proto

package legacypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// POOLTYPE mirrors nodejs-pool's real data.proto POOLTYPE enum exactly
// (field values are part of the real wire contract -- do not renumber).
type POOLTYPE int32

const (
	POOLTYPE_PPLNS POOLTYPE = 0
	POOLTYPE_PPS   POOLTYPE = 1
	POOLTYPE_PROP  POOLTYPE = 2
	POOLTYPE_SOLO  POOLTYPE = 3
)

// Enum value maps for POOLTYPE.
var (
	POOLTYPE_name = map[int32]string{
		0: "PPLNS",
		1: "PPS",
		2: "PROP",
		3: "SOLO",
	}
	POOLTYPE_value = map[string]int32{
		"PPLNS": 0,
		"PPS":   1,
		"PROP":  2,
		"SOLO":  3,
	}
)

func (x POOLTYPE) Enum() *POOLTYPE {
	p := new(POOLTYPE)
	*p = x
	return p
}

func (x POOLTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (POOLTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_legacyproto_legacy_proto_enumTypes[0].Descriptor()
}

func (POOLTYPE) Type() protoreflect.EnumType {
	return &file_internal_legacyproto_legacy_proto_enumTypes[0]
}

func (x POOLTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *POOLTYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = POOLTYPE(num)
	return nil
}

// Deprecated: Use POOLTYPE.Descriptor instead.
func (POOLTYPE) EnumDescriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{0}
}

// MESSAGETYPE mirrors nodejs-pool's real data.proto MESSAGETYPE enum
// exactly (field values are part of the real wire contract -- do not
// renumber).
type MESSAGETYPE int32

const (
	MESSAGETYPE_SHARE        MESSAGETYPE = 0
	MESSAGETYPE_BLOCK        MESSAGETYPE = 1
	MESSAGETYPE_INVALIDSHARE MESSAGETYPE = 2
)

// Enum value maps for MESSAGETYPE.
var (
	MESSAGETYPE_name = map[int32]string{
		0: "SHARE",
		1: "BLOCK",
		2: "INVALIDSHARE",
	}
	MESSAGETYPE_value = map[string]int32{
		"SHARE":        0,
		"BLOCK":        1,
		"INVALIDSHARE": 2,
	}
)

func (x MESSAGETYPE) Enum() *MESSAGETYPE {
	p := new(MESSAGETYPE)
	*p = x
	return p
}

func (x MESSAGETYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MESSAGETYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_legacyproto_legacy_proto_enumTypes[1].Descriptor()
}

func (MESSAGETYPE) Type() protoreflect.EnumType {
	return &file_internal_legacyproto_legacy_proto_enumTypes[1]
}

func (x MESSAGETYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MESSAGETYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MESSAGETYPE(num)
	return nil
}

// Deprecated: Use MESSAGETYPE.Descriptor instead.
func (MESSAGETYPE) EnumDescriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{1}
}

// WSData is the real outer envelope every `/leafApi` POST body decodes
// as (see lib/remoteShare.js: `global.protos.WSData.decode(req.body)`).
// Auth is carried as the plain `key` string field, checked with `!==`
// server-side against `global.config.api.authKey` -- there is no
// HTTP-header-based auth on this endpoint at all.
type WSData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       *MESSAGETYPE           `protobuf:"varint,1,req,name=msgType,enum=legacy.MESSAGETYPE" json:"msgType,omitempty"`
	Key           *string                `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Msg           []byte                 `protobuf:"bytes,3,req,name=msg" json:"msg,omitempty"`
	ExInt         *int32                 `protobuf:"varint,4,req,name=exInt" json:"exInt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSData) Reset() {
	*x = WSData{}
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSData) ProtoMessage() {}

func (x *WSData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSData.ProtoReflect.Descriptor instead.
func (*WSData) Descriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{0}
}

func (x *WSData) GetMsgType() MESSAGETYPE {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return MESSAGETYPE_SHARE
}

func (x *WSData) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *WSData) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WSData) GetExInt() int32 {
	if x != nil && x.ExInt != nil {
		return *x.ExInt
	}
	return 0
}

// InvalidShare mirrors nodejs-pool's real data.proto InvalidShare
// message exactly. go-crypto-pool's LegacyTransport does not currently
// construct/send this message type (see legacytransport's doc comment)
// -- it is included here purely for schema completeness/fidelity with
// the real wire format, and is covered by this package's round-trip
// test.
type InvalidShare struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentAddress *string                `protobuf:"bytes,1,req,name=paymentAddress" json:"paymentAddress,omitempty"`
	PaymentID      *string                `protobuf:"bytes,2,opt,name=paymentID" json:"paymentID,omitempty"`
	Identifier     *string                `protobuf:"bytes,3,req,name=identifier" json:"identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvalidShare) Reset() {
	*x = InvalidShare{}
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidShare) ProtoMessage() {}

func (x *InvalidShare) ProtoReflect() protoreflect.Message {
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidShare.ProtoReflect.Descriptor instead.
func (*InvalidShare) Descriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidShare) GetPaymentAddress() string {
	if x != nil && x.PaymentAddress != nil {
		return *x.PaymentAddress
	}
	return ""
}

func (x *InvalidShare) GetPaymentID() string {
	if x != nil && x.PaymentID != nil {
		return *x.PaymentID
	}
	return ""
}

func (x *InvalidShare) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

// Share mirrors nodejs-pool's real data.proto Share message exactly.
type Share struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Shares         *int32                 `protobuf:"varint,1,req,name=shares" json:"shares,omitempty"`
	PaymentAddress *string                `protobuf:"bytes,2,req,name=paymentAddress" json:"paymentAddress,omitempty"`
	FoundBlock     *bool                  `protobuf:"varint,3,req,name=foundBlock" json:"foundBlock,omitempty"`
	PaymentID      *string                `protobuf:"bytes,4,opt,name=paymentID" json:"paymentID,omitempty"`
	TrustedShare   *bool                  `protobuf:"varint,5,req,name=trustedShare" json:"trustedShare,omitempty"`
	PoolType       *POOLTYPE              `protobuf:"varint,6,req,name=poolType,enum=legacy.POOLTYPE" json:"poolType,omitempty"`
	PoolID         *int32                 `protobuf:"varint,7,req,name=poolID" json:"poolID,omitempty"`
	BlockDiff      *int64                 `protobuf:"varint,8,req,name=blockDiff" json:"blockDiff,omitempty"`
	Bitcoin        *bool                  `protobuf:"varint,9,req,name=bitcoin" json:"bitcoin,omitempty"`
	BlockHeight    *int32                 `protobuf:"varint,10,req,name=blockHeight" json:"blockHeight,omitempty"`
	Timestamp      *int64                 `protobuf:"varint,11,req,name=timestamp" json:"timestamp,omitempty"`
	Identifier     *string                `protobuf:"bytes,12,req,name=identifier" json:"identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{2}
}

func (x *Share) GetShares() int32 {
	if x != nil && x.Shares != nil {
		return *x.Shares
	}
	return 0
}

func (x *Share) GetPaymentAddress() string {
	if x != nil && x.PaymentAddress != nil {
		return *x.PaymentAddress
	}
	return ""
}

func (x *Share) GetFoundBlock() bool {
	if x != nil && x.FoundBlock != nil {
		return *x.FoundBlock
	}
	return false
}

func (x *Share) GetPaymentID() string {
	if x != nil && x.PaymentID != nil {
		return *x.PaymentID
	}
	return ""
}

func (x *Share) GetTrustedShare() bool {
	if x != nil && x.TrustedShare != nil {
		return *x.TrustedShare
	}
	return false
}

func (x *Share) GetPoolType() POOLTYPE {
	if x != nil && x.PoolType != nil {
		return *x.PoolType
	}
	return POOLTYPE_PPLNS
}

func (x *Share) GetPoolID() int32 {
	if x != nil && x.PoolID != nil {
		return *x.PoolID
	}
	return 0
}

func (x *Share) GetBlockDiff() int64 {
	if x != nil && x.BlockDiff != nil {
		return *x.BlockDiff
	}
	return 0
}

func (x *Share) GetBitcoin() bool {
	if x != nil && x.Bitcoin != nil {
		return *x.Bitcoin
	}
	return false
}

func (x *Share) GetBlockHeight() int32 {
	if x != nil && x.BlockHeight != nil {
		return *x.BlockHeight
	}
	return 0
}

func (x *Share) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Share) GetIdentifier() string {
	if x != nil && x.Identifier != nil {
		return *x.Identifier
	}
	return ""
}

// Block mirrors nodejs-pool's real data.proto Block message exactly.
// Note there is no height field here -- height only ever traveled via
// the outer WSData.exInt (confirmed from lib/pool.js's
// `storeBlock(job.height, ...)` call, forwarded verbatim by
// remoteShare.js as `msgData.exInt`).
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          *string                `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Difficulty    *int64                 `protobuf:"varint,2,req,name=difficulty" json:"difficulty,omitempty"`
	Shares        *int64                 `protobuf:"varint,3,req,name=shares" json:"shares,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,4,req,name=timestamp" json:"timestamp,omitempty"`
	PoolType      *POOLTYPE              `protobuf:"varint,5,req,name=poolType,enum=legacy.POOLTYPE" json:"poolType,omitempty"`
	Unlocked      *bool                  `protobuf:"varint,6,req,name=unlocked" json:"unlocked,omitempty"`
	Valid         *bool                  `protobuf:"varint,7,req,name=valid" json:"valid,omitempty"`
	Value         *int64                 `protobuf:"varint,8,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_internal_legacyproto_legacy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_internal_legacyproto_legacy_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetHash() string {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return ""
}

func (x *Block) GetDifficulty() int64 {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return 0
}

func (x *Block) GetShares() int64 {
	if x != nil && x.Shares != nil {
		return *x.Shares
	}
	return 0
}

func (x *Block) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Block) GetPoolType() POOLTYPE {
	if x != nil && x.PoolType != nil {
		return *x.PoolType
	}
	return POOLTYPE_PPLNS
}

func (x *Block) GetUnlocked() bool {
	if x != nil && x.Unlocked != nil {
		return *x.Unlocked
	}
	return false
}

func (x *Block) GetValid() bool {
	if x != nil && x.Valid != nil {
		return *x.Valid
	}
	return false
}

func (x *Block) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_internal_legacyproto_legacy_proto protoreflect.FileDescriptor

const file_internal_legacyproto_legacy_proto_rawDesc = "" +
	"\n" +
	"!internal/legacyproto/legacy.proto\x12\x06legacy\"q\n" +
	"\x06WSData\x12-\n" +
	"\amsgType\x18\x01 \x02(\x0e2\x13.legacy.MESSAGETYPER\amsgType\x12\x10\n" +
	"\x03key\x18\x02 \x02(\tR\x03key\x12\x10\n" +
	"\x03msg\x18\x03 \x02(\fR\x03msg\x12\x14\n" +
	"\x05exInt\x18\x04 \x02(\x05R\x05exInt\"t\n" +
	"\fInvalidShare\x12&\n" +
	"\x0epaymentAddress\x18\x01 \x02(\tR\x0epaymentAddress\x12\x1c\n" +
	"\tpaymentID\x18\x02 \x01(\tR\tpaymentID\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x02(\tR\n" +
	"identifier\"\x87\x03\n" +
	"\x05Share\x12\x16\n" +
	"\x06shares\x18\x01 \x02(\x05R\x06shares\x12&\n" +
	"\x0epaymentAddress\x18\x02 \x02(\tR\x0epaymentAddress\x12\x1e\n" +
	"\n" +
	"foundBlock\x18\x03 \x02(\bR\n" +
	"foundBlock\x12\x1c\n" +
	"\tpaymentID\x18\x04 \x01(\tR\tpaymentID\x12\"\n" +
	"\ftrustedShare\x18\x05 \x02(\bR\ftrustedShare\x12,\n" +
	"\bpoolType\x18\x06 \x02(\x0e2\x10.legacy.POOLTYPER\bpoolType\x12\x16\n" +
	"\x06poolID\x18\a \x02(\x05R\x06poolID\x12\x1c\n" +
	"\tblockDiff\x18\b \x02(\x03R\tblockDiff\x12\x18\n" +
	"\abitcoin\x18\t \x02(\bR\abitcoin\x12 \n" +
	"\vblockHeight\x18\n" +
	" \x02(\x05R\vblockHeight\x12\x1c\n" +
	"\ttimestamp\x18\v \x02(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"identifier\x18\f \x02(\tR\n" +
	"identifier\"\xe7\x01\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x02(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x02(\x03R\n" +
	"difficulty\x12\x16\n" +
	"\x06shares\x18\x03 \x02(\x03R\x06shares\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x02(\x03R\ttimestamp\x12,\n" +
	"\bpoolType\x18\x05 \x02(\x0e2\x10.legacy.POOLTYPER\bpoolType\x12\x1a\n" +
	"\bunlocked\x18\x06 \x02(\bR\bunlocked\x12\x14\n" +
	"\x05valid\x18\a \x02(\bR\x05valid\x12\x14\n" +
	"\x05value\x18\b \x01(\x03R\x05value*2\n" +
	"\bPOOLTYPE\x12\t\n" +
	"\x05PPLNS\x10\x00\x12\a\n" +
	"\x03PPS\x10\x01\x12\b\n" +
	"\x04PROP\x10\x02\x12\b\n" +
	"\x04SOLO\x10\x03*5\n" +
	"\vMESSAGETYPE\x12\t\n" +
	"\x05SHARE\x10\x00\x12\t\n" +
	"\x05BLOCK\x10\x01\x12\x10\n" +
	"\fINVALIDSHARE\x10\x02BAZ?github.com/Snipa22/go-crypto-pool/internal/legacyproto;legacypb"

var (
	file_internal_legacyproto_legacy_proto_rawDescOnce sync.Once
	file_internal_legacyproto_legacy_proto_rawDescData []byte
)

func file_internal_legacyproto_legacy_proto_rawDescGZIP() []byte {
	file_internal_legacyproto_legacy_proto_rawDescOnce.Do(func() {
		file_internal_legacyproto_legacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_legacyproto_legacy_proto_rawDesc), len(file_internal_legacyproto_legacy_proto_rawDesc)))
	})
	return file_internal_legacyproto_legacy_proto_rawDescData
}

var file_internal_legacyproto_legacy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_legacyproto_legacy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_legacyproto_legacy_proto_goTypes = []any{
	(POOLTYPE)(0),        // 0: legacy.POOLTYPE
	(MESSAGETYPE)(0),     // 1: legacy.MESSAGETYPE
	(*WSData)(nil),       // 2: legacy.WSData
	(*InvalidShare)(nil), // 3: legacy.InvalidShare
	(*Share)(nil),        // 4: legacy.Share
	(*Block)(nil),        // 5: legacy.Block
}
var file_internal_legacyproto_legacy_proto_depIdxs = []int32{
	1, // 0: legacy.WSData.msgType:type_name -> legacy.MESSAGETYPE
	0, // 1: legacy.Share.poolType:type_name -> legacy.POOLTYPE
	0, // 2: legacy.Block.poolType:type_name -> legacy.POOLTYPE
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_legacyproto_legacy_proto_init() }
func file_internal_legacyproto_legacy_proto_init() {
	if File_internal_legacyproto_legacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_legacyproto_legacy_proto_rawDesc), len(file_internal_legacyproto_legacy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_legacyproto_legacy_proto_goTypes,
		DependencyIndexes: file_internal_legacyproto_legacy_proto_depIdxs,
		EnumInfos:         file_internal_legacyproto_legacy_proto_enumTypes,
		MessageInfos:      file_internal_legacyproto_legacy_proto_msgTypes,
	}.Build()
	File_internal_legacyproto_legacy_proto = out.File
	file_internal_legacyproto_legacy_proto_goTypes = nil
	file_internal_legacyproto_legacy_proto_depIdxs = nil
}
